// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Microsoft.Windows.AI.h"
#include "Microsoft.Windows.AI.ContentSafety.h"

/* Forward Declarations */
#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_FWD_DEFINED__

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel;

#if !defined(____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel;

    typedef struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
        __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl;

    interface __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel;

    typedef struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl;

    interface __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationCompletedHandler_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult_FWD_DEFINED__

typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

#if !defined(____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* handler);
    HRESULT (STDMETHODCALLTYPE* get_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** result);
    HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CIAIFeatureReadyResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double;

    typedef struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double* asyncInfo,
        DOUBLE progressInfo);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl;

    interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_doubleVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

#if !defined(____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* handler);
    HRESULT (STDMETHODCALLTYPE* get_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING* asyncInfo,
        HSTRING progressInfo);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING_INTERFACE_DEFINED__
    
typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

#if !defined(____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* asyncInfo,
        enum __x_ABI_CWindows_CFoundation_CAsyncStatus asyncStatus);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* handler);
    HRESULT (STDMETHODCALLTYPE* get_Progress)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* put_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* handler);
    HRESULT (STDMETHODCALLTYPE* get_Completed)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgressCompletedHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* GetResults)(__x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult** result);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__
    
#if !defined(____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING;

    typedef struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING* asyncInfo,
        HSTRING progressInfo);

        END_INTERFACE
    } __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl;

    interface __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING
    {
        CONST_VTBL struct __x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRINGVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FIAsyncOperationProgressHandler_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING_INTERFACE_DEFINED__
    
typedef enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState;

#ifndef ____x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions_FWD_DEFINED__
#define ____x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions_FWD_DEFINED__
    typedef interface __x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions __x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions;

#endif // ____x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions_FWD_DEFINED__

typedef enum __x_ABI_CWindows_CFoundation_CAsyncStatus __x_ABI_CWindows_CFoundation_CAsyncStatus;

#ifndef ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIAsyncInfo __x_ABI_CWindows_CFoundation_CIAsyncInfo;

#endif // ____x_ABI_CWindows_CFoundation_CIAsyncInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

typedef enum __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus;

enum __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus
    {
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_Complete = 0,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_InProgress = 1,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_BlockedByPolicy = 2,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_PromptLargerThanContext = 3,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_PromptBlockedByContentModeration = 4,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_ResponseBlockedByContentModeration = 5,
    __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus_Error = 6,
};

#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContextVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContextVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelContext_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptionsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Temperature)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        FLOAT* value);
    HRESULT (STDMETHODCALLTYPE* put_Temperature)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        FLOAT value);
    HRESULT (STDMETHODCALLTYPE* get_TopP)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        FLOAT* value);
    HRESULT (STDMETHODCALLTYPE* put_TopP)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        FLOAT value);
    HRESULT (STDMETHODCALLTYPE* get_TopK)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        UINT32* value);
    HRESULT (STDMETHODCALLTYPE* put_TopK)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        UINT32 value);
    HRESULT (STDMETHODCALLTYPE* get_ContentFilterOptions)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions** value);
    HRESULT (STDMETHODCALLTYPE* put_ContentFilterOptions)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CContentSafety_CIContentFilterOptions* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptionsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptionsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelOptions_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Text)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Status)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
        enum __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus* value);
    HRESULT (STDMETHODCALLTYPE* get_ExtendedError)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult* This,
        HRESULT* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResultVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResultVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelResponseResult_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStaticsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetReadyState)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
        enum __x_ABI_CMicrosoft_CWindows_CAI_CAIFeatureReadyState* result);
    HRESULT (STDMETHODCALLTYPE* EnsureReadyAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CAIFeatureReadyResult_double** operation);
    HRESULT (STDMETHODCALLTYPE* CreateAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics* This,
        __x_ABI_C__FIAsyncOperation_1___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModel** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStaticsVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStaticsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModelStatics_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* RewriteAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter* This,
        HSTRING text,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* languageModel,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriter** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextRewriterFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* SummarizeAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
        HSTRING text,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING** operation);
    HRESULT (STDMETHODCALLTYPE* SummarizeParagraphAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer* This,
        HSTRING text,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CLanguageModelResponseResult_HSTRING** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* languageModel,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizer** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextSummarizerFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* ConvertAsync)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter* This,
        HSTRING text,
        __x_ABI_C__FIAsyncOperationWithProgress_2___x_ABI_CMicrosoft__CWindows__CAI__CText__CTextToTableResponseResult_HSTRING** operation);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInstance)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory* This,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CILanguageModel* languageModel,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverter** value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactoryVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableConverterFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResultVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetRows)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
        UINT32* resultLength,
        __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow*** result);
    HRESULT (STDMETHODCALLTYPE* get_Status)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
        enum __x_ABI_CMicrosoft_CWindows_CAI_CText_CLanguageModelResponseStatus* value);
    HRESULT (STDMETHODCALLTYPE* get_ExtendedError)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult* This,
        HRESULT* value);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResultVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResultVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableResponseResult_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_INTERFACE_DEFINED__)
    #define ____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_INTERFACE_DEFINED__
    typedef struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRowVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetColumns)(__x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow* This,
        UINT32* resultLength,
        HSTRING** result);

        END_INTERFACE
    } __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRowVtbl;

    interface __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow
    {
        CONST_VTBL struct __x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRowVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow;
#endif /* !defined(____x_ABI_CMicrosoft_CWindows_CAI_CText_CITextToTableRow_INTERFACE_DEFINED__) */
    
